import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/share/Header";
import RightMenu from "@/components/share/RightMenu";
import Footer from "@/components/share/Footer";
import ScrollToTop from "@/components/share/ScrollToTop";

export const metadata: Metadata = {
  title: "Nhãn mác xịn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link rel="icon" href="/logo.svg" type="image/png" sizes="32x32" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" />
      </head>
      <body >
        <Header />
        <RightMenu/>
        {children}
        <ScrollToTop />
        <Footer/>
        {/* {children} */}
      </body>
    </html>
  );
}
